[package]
name = "gba-convert-images"
version = "0.1.0"
authors = ["Tom Streller <tom.streller@tutti.ch>"]
edition = "2018"

[dependencies]
toml = "0.5"
image = "0.23"

[dependencies.serde]
version = "1.0"
features = ["derive"]

[lib]
proc-macro = true
