[package]
name = "gba_convert"
version = "0.1.0"
authors = ["Tom Streller <tom.streller@tutti.ch>"]
edition = "2018"

[dependencies]
image = "0.23"
quote = "1.0"
syn = "0.15"

[lib]
proc-macro = true

[[example]]
name = "bitmap"
